# Generated by Django 5.1.2 on 2024-10-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_related_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, to='store.product', verbose_name='მსგავსი პროდუქტები'),
        ),
    ]
