# Generated by Django 5.1.2 on 2024-10-19 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_related_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreviews',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='პროდუქტი'),
            preserve_default=False,
        ),
    ]
