# Generated by Django 5.1.2 on 2024-10-23 17:40

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, help_text='ატვირთეთ ფოტოსურათი', null=True, upload_to='', verbose_name='სურათი'),
        ),
    ]
