# Generated by Django 5.1.2 on 2024-10-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_category_product_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_organic',
        ),
        migrations.RemoveField(
            model_name='product',
            name='on_sale',
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='store.producttags'),
        ),
    ]
