# Generated by Django 5.1.2 on 2024-10-23 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_producttags_remove_product_is_organic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='related_products',
        ),
    ]
