# Generated by Django 5.1.2 on 2024-10-19 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.PositiveIntegerField(verbose_name='რაოდენობა')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='პროდუქტი')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='მომხმარებელი')),
                ('flat_rate', models.IntegerField(verbose_name='მიტანა')),
                ('items', models.ManyToManyField(to='order.cartitems', verbose_name='პროდუქტები')),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='სახელი')),
                ('last_name', models.CharField(max_length=100, verbose_name='გვარი')),
                ('order_address', models.CharField(max_length=100, verbose_name='მისამართი')),
                ('city', models.CharField(max_length=100, verbose_name='ქალაქი')),
                ('country', models.CharField(max_length=100, verbose_name='ქვეყანა')),
                ('postcode', models.IntegerField(verbose_name='საფოსტო კოდი')),
                ('mobile', models.CharField(max_length=100, verbose_name='ტელეფონის ნომერი')),
                ('email', models.EmailField(max_length=100, verbose_name='მეილი')),
                ('create_account', models.BooleanField(default=False, verbose_name='შექმენი ანგარიში')),
                ('order_notes', models.TextField(verbose_name='შეკვეთის დეტალები')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='შეკვეთის თარიღი')),
                ('order_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='მომხმარებელი')),
                ('product_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.cart', verbose_name='პროდუქტები')),
            ],
        ),
    ]
