# Generated by Django 5.1.2 on 2024-10-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_cartitems_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='order.cartitems', verbose_name='პროდუქტები'),
        ),
    ]
