# Generated by Django 5.1.2 on 2024-10-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_cartitems_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='total_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='მთლიანი ფასი'),
        ),
    ]
