# Generated by Django 5.1.2 on 2024-10-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_cartitems_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='product_quantity',
            field=models.IntegerField(verbose_name='რაოდენობა'),
        ),
    ]
