# Generated by Django 5.1.2 on 2024-10-25 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_cartitems_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='total_price',
        ),
    ]
