# Generated by Django 5.1.2 on 2024-10-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_remove_cartitems_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='total_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='მთლიანი ფასი'),
        ),
    ]
