# Generated by Django 5.1.2 on 2024-10-25 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_cartitems_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='total_price',
        ),
    ]
